# Generated by Django 4.2.17 on 2024-12-26 03:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создании задачи'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='date_end',
            field=models.DateTimeField(null=True, verbose_name='Дата и время, когда задача должна быть выполнена'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_start',
            field=models.DateTimeField(null=True, verbose_name='Дата и время, когда нужно начать задачу'),
        ),
    ]
