# Generated by Django 4.2.17 on 2025-01-01 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_date_add_alter_task_date_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_statused', to='tasks.status', verbose_name='Текущий статус')),
                ('next_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_statused', to='tasks.status', verbose_name='Следующий статус')),
            ],
            options={
                'verbose_name': 'переход статуса',
                'verbose_name_plural': 'Переходы статусов',
                'db_table': 'tasks_status_transition',
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
