# Generated by Django 4.2.17 on 2025-01-04 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_statustransition'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='current_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.status', verbose_name='Текущий статус'),
        ),
    ]
